### PR TITLE
Convert project to .net standard 2.0

### PR DESCRIPTION
**Pull request by Macjon**
Converted the library to a .net standard 2.0 library.

### CODE REVIEW

**Comment by Macjon** [comment]
@dnarotama I converted the project on Visual Studio for Mac so I couldn't check if the Tests are still green. Can you please verify if all the tests are green and create a new nuget package?

**Comment by Macjon** [comment]
@mi9-benho anybody??

**Comment by dnarotama** [comment]
Hi @Macjon , 

My Apology for the delay, we have created a ticket for this review. We'll let you know once this has been reviewed and approved.

**Comment by dnarotama** [comment]
Hi @Macjon ,

We have checked the unit tests, one of tests needs to be amended, but we'll do that separate to your pull request.

We are going to merge your pull request today.

**Pull request merged**
